[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
crudapp = "8bgEPmmRk3N7Wtz1srGiz7BQ6ojG4cVhGHndnASiUQGQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/dani/.config/solana/wallets/test_wallet.json"
# (optional) you can force a specific RPC if you want:
# url = "https://api.devnet.solana.com"

[scripts]
test = "vitest"
