[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
crudapp = "2wtMCx1PDGqCHfCYnfKrhQRrANFWeMxNSr7eAPJrhrmv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet  = "/home/dani/.config/solana/wallets/mainwallet.json"

[scripts]
test = "vitest"
